Name:           ros-jade-naoqi-dashboard
Version:        0.1.3
Release:        0%{?dist}
Summary:        ROS naoqi_dashboard package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/naoqi_dashboard
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-jade-diagnostic-aggregator
Requires:       ros-jade-diagnostic-common-diagnostics
Requires:       ros-jade-diagnostic-msgs
Requires:       ros-jade-naoqi-bridge-msgs >= 0.0.4
Requires:       ros-jade-rqt-robot-dashboard
Requires:       ros-jade-rqt-robot-monitor
BuildRequires:  ros-jade-catkin
Conflicts:      ros-jade-nao-dashboard
Conflicts:      ros-jade-nao-viz

%description
naoqi_dashboard is a GUI for monitoring the state of an ALdebaran robot. It is a
port of pr2_dashboard and shows status information like battery status, joint
temperatures, and joint stiffness, as well as integrating ROS tools like
rqt_console and rqt_robot_monitor.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Wed Aug 26 2015 Vincent Rabaud <vincent.rabaud@gmail.com> - 0.1.3-0
- Autogenerated by Bloom

